version: '3'
services:
  nestjs-app:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "npm install && npm run start:prod"
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_NAME=realtor

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: realtor
    ports:
      - "5432:5432"
