import { ContractDto } from './contract.dto';
import { FintracDto } from './fintrac.dto';
import { IdentityDto } from './identity.dto';
import { MemberDto } from './member.dto';
import { VerificationDto } from './verification.dto';
import { ProfileDto } from './profile.dto';
import { VerificationRequestDto } from './verification_request.dto';
import { VerificationHitsDto } from './verification_hits.dto';
import { FintracRiskDto } from './fintrac_risk.dto';
import { FintracVerificationDto } from './fintrac_verification.dto';

export class ContactDto {
  name!: string;
  email!: string;
  phone!: string;
  address?: string;
  city?: string;
  province?: string;
  postal?: string;
  country?: string;
  description?: string;
  corp_number?: string;
  corp_legal_name?: string;
  corp_province?: string;
  corp_country?: string;
  type!: 'individual' | 'company' | 'group';
  status!: 'active' | 'archived';
  avatar_sm?: string;
  avatar_md?: string;
  avatar_lg?: string;
  profile_id?: number;
  has_completed_identity?: boolean;
  has_active_contract?: boolean;
  has_fintrac_score?: boolean;
  profile?: ProfileDto;
  identity?: IdentityDto;
  verifications?: VerificationDto[];
  verification_request?: VerificationRequestDto[];
  verification_hits?: VerificationHitsDto[];
  contract?: ContractDto;
  fintracs?: FintracDto[];
  fintrac_risk?: FintracRiskDto;
  fintrac_verification?: FintracVerificationDto;
  members?: MemberDto[];
}
